"""Create the SharePoint Lists defined by a schema file via Microsoft Graph.

Generic: pass any schema JSON from schema/ (or one generated by analyze.py).
Idempotent: existing lists are kept; any columns missing from them are added.
Indexes are declared at creation time, before any list grows past the 5,000-item
view threshold, which is what keeps large-list views fast.

Usage:  python provision.py --schema ..\\schema\\transcription_tracker.json
"""

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path

from auth import get_site_id
from graph_client import find_list, graph_request, make_session

HUB_LIST = "AIT Projects"


def column_payload(col: dict) -> dict:
    return {k: v for k, v in col.items() if k not in ("titleColumnMeaning",)}


def provision_list(session, site_id, spec) -> None:
    name = spec["displayName"]
    existing = find_list(session, site_id, name)
    if existing is None:
        body = {
            "displayName": name,
            "description": spec.get("description", ""),
            "columns": [column_payload(c) for c in spec["columns"]],
            "list": {"template": "genericList"},
        }
        r = graph_request(session, "POST", f"/sites/{site_id}/lists", json=body)
        if not r.ok:
            sys.exit(f"FAILED creating list {name!r}: {r.status_code} {r.text}")
        print(f"created list {name!r} with {len(spec['columns'])} columns")
        return

    list_id = existing["id"]
    r = graph_request(session, "GET", f"/sites/{site_id}/lists/{list_id}/columns?$top=200")
    r.raise_for_status()
    have = {c["name"].lower() for c in r.json().get("value", [])}
    added = 0
    for col in spec["columns"]:
        if col["name"].lower() in have:
            continue
        r = graph_request(
            session, "POST", f"/sites/{site_id}/lists/{list_id}/columns", json=column_payload(col)
        )
        if not r.ok:
            print(f"  WARN could not add column {col['name']!r} to {name!r}: {r.status_code} {r.text}")
        else:
            added += 1
    print(f"list {name!r} already exists - added {added} missing column(s)")


def register_project(session, site_id, project_name, site_url, pm="", client="",
                     service_type="", start_date=None) -> None:
    """Upsert a row in the 'AIT Projects' hub list so cross-project automation
    (overdue digests, quality rollups) automatically picks up this tracker.

    No-op (with a friendly note) if the hub list isn't on the site yet, so it
    never blocks provisioning. Idempotent: keyed on the project name, so
    re-provisioning updates the same registry row instead of duplicating it.
    """
    hub = find_list(session, site_id, HUB_LIST)
    if hub is None:
        print(f"  registry: {HUB_LIST!r} hub list not found on this site - skipped. "
              f"(Provision ait_master_hub.json to enable cross-project automation.)")
        return

    existing_id = None
    r = graph_request(
        session, "GET",
        f"/sites/{site_id}/lists/{hub['id']}/items?$expand=fields(select=Title)&$top=500",
    )
    if r.ok:
        for it in r.json().get("value", []):
            if (it.get("fields", {}).get("Title") or "").strip().lower() == project_name.strip().lower():
                existing_id = it["id"]
                break

    fields = {"Title": project_name, "TrackerSiteURL": site_url, "ProjectStatus": "Active"}
    if pm:
        fields["PMOwner"] = pm
    if client:
        fields["Client"] = client
    if service_type:
        fields["ServiceType"] = service_type
    if start_date:
        fields["StartDate"] = start_date

    if existing_id:
        r = graph_request(session, "PATCH",
                          f"/sites/{site_id}/lists/{hub['id']}/items/{existing_id}/fields", json=fields)
        print(f"  registry: updated {HUB_LIST} row for {project_name!r}"
              if r.ok else f"  registry: update failed ({r.status_code}) {r.text[:200]}")
    else:
        r = graph_request(session, "POST",
                          f"/sites/{site_id}/lists/{hub['id']}/items", json={"fields": fields})
        print(f"  registry: registered {project_name!r} in {HUB_LIST}"
              if r.ok else f"  registry: add failed ({r.status_code}) {r.text[:200]}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True, help="schema JSON (see schema/ or analyze.py output)")
    ap.add_argument("--register-pm", default="", help="PM owner to record in the AIT Projects registry")
    ap.add_argument("--register-client", default="", help="client name to record in the registry")
    ap.add_argument("--no-register", action="store_true", help="skip writing to the AIT Projects registry")
    args = ap.parse_args()
    schema = json.loads(Path(args.schema).read_text(encoding="utf-8"))
    session = make_session()
    site_id = get_site_id(session)
    print(f"site resolved: {site_id}")
    for spec in schema["lists"]:
        provision_list(session, site_id, spec)

    # Auto-register this tracker in the hub registry, unless this IS the hub
    # schema (which contains the AIT Projects list itself) or registration is off.
    is_hub = any(l["displayName"] == HUB_LIST for l in schema["lists"])
    if not is_hub and not args.no_register:
        site_url = f"https://{os.getenv('SITE_HOSTNAME', '')}{os.getenv('SITE_PATH', '')}"
        register_project(
            session, site_id,
            project_name=schema.get("project", schema["lists"][0]["displayName"]),
            site_url=site_url,
            pm=args.register_pm or os.getenv("AIT_PM_OWNER", ""),
            client=args.register_client,
            service_type=schema.get("serviceType", ""),
            start_date=date.today().strftime("%Y-%m-%dT00:00:00Z"),
        )
    print("done.")


if __name__ == "__main__":
    main()
